### ISSUE TITLE
subfolder support for game dumps

### ISSUE THREAD

**Issue by briantho** [FIX94/wudump#1]
Title says it all. Rather than dumping a game to sd:/wudump why not have wudump create a subfolder such as sd:/wudump/gamename [gameid] 
This way, it won't be necessary to unplug the sd, plug into computer, copy files to pc, delete files on sd, reinsert sd card, launch wudump again and then dump next game, if you were dumping multiple games. 
Instead wudump should just change the output filename or put it in a subfolder such as 
Super Smash Bros for Wii U [AXFE01]
so it won't overwrite the game dump the next time wudump is launched. Also, thanks for creating this great and very usefully homebrew.

**Comment by FIX94** [comment]
go check out the new version.
